<?php
$arr=array();
$socks=array();
co::create(function()use(&$arr,&$socks){
    $cid=co::get_current_cid();
    $fd=null;
    for(;;){
        if(empty($socks)&&$fd==null){
            $arr[] =$cid;
            co::yield();
        }
        if(!empty($socks)&&$fd==null){
        $fd=array_shift($socks);
        }
var_dump("test");
var_dump($fd);
    }
});

co::create(function()use(&$arr,&$socks){
    $cid=co::get_current_cid();
    $fd=null;
    for(;;){
        if(empty($socks)&&$fd==null){
            $arr[] =$cid;
            co::yield();
        }
        if(!empty($socks)&&$fd==null){
        $fd=array_shift($socks);
        }
var_dump("test");
var_dump($fd);
    }
});
co::create(function()use(&$sock,&$arr,&$socks){
    for(;;){
    if(empty($arr)){
        co::sleep(1);
        continue;
        }
       $fd="foo";
       $socks[]=$fd;
       $cid=array_shift($arr);
       co::resume($cid);
    }
});
co::event_loop();
